
server:
  port: 8088
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/forthproject?characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hunt.jsontest.pojo